### ISSUE TITLE
Nested properties

### ISSUE THREAD

**Issue by leopaini** [TheRealSyler/sass-formatter#20]
Hello, I'm trying to make some nested properties, and the automatic indent doesn't allow me to do it.

Example:
```
border:
 style: dashed 
 width: 30px
 color: blue
```
