### ISSUE TITLE
Nesting doesn't work properly

### ISSUE THREAD

**Issue by lycoTi** [TheRealSyler/sass-formatter#68]
## Nesting properties
There some properties that start with the same prefix that acts as a kind of namespace, like transition, margin, padding, font...
I can nest them to cut that prefix and work more with nesting, but the formatter ignores that nest, I can't tell if there is an option to turn on that functionality, but if not, will be good to work on it.

My code just broke when I tried to format the doc with the formatter, forcing me to refactor the whole code.

Here is some examples I found at sass's documentation:

```
.enlarge
  font-size: 14px
  transition:
    property: font-size
    duration: 4s
    delay: 2s

  &:hover
    font-size: 36px
```
```
.info-page
  margin: auto
    bottom: 10px
    top: 2px
```

## From Sass's documentation

![sass nesting](https://user-images.githubusercontent.com/91505691/206715460-8bd8b4fe-e28e-44cf-a4dc-f472b8200b84.png)
[sass's documentation](https://sass-lang.com/documentation/style-rules/declarations)

**Desktop :**
 - OS: [e.g. windows 10]
 - Version [e.g. 1.8.23]

**Additional context**
